export default [
  { src: "https://i.imgur.com/SRMnG7x.jpg", price: 20 },
  { src: "https://i.imgur.com/Lek6YZb.jpg", price: 20 },
  // 沙奈 AR 太貴，先等等
  // { "src": "https://i.imgur.com/ZFyDMbm.jpg", "price": 20 },
  // { "src": "https://i.imgur.com/LC0OAkQ.jpg", "price": 20 },
  { src: "https://i.imgur.com/nnPTpoH.jpg", price: 20 },
  { src: "https://i.imgur.com/lgigEOF.jpg", price: 20 },
  { src: "https://i.imgur.com/LcKcWHi.jpg", price: 20 },
  { src: "https://i.imgur.com/8MNiNjd.jpg", price: 20 },
  { src: "https://i.imgur.com/bFGpO6p.jpg", price: 80 },
  // 沙奈 sr
  // { "src": "https://i.imgur.com/MnA2Gnj.jpg", "price": 100 },
  { src: "https://i.imgur.com/WZMvgfU.jpg", price: 50 },
  { src: "https://i.imgur.com/QvD3Kzr.jpg", price: 40 },
  // 沙奈 sar
  // { "src": "https://i.imgur.com/nsZFz1x.jpg", "price": 1200 },
  { src: "https://i.imgur.com/LJ8hUgk.jpg", price: 150 },
  { src: "https://i.imgur.com/OJLHEnO.jpg", price: 300 },
  { src: "https://i.imgur.com/xDZXyBr.jpg", price: 20 },
  { src: "https://i.imgur.com/hJGMIt5.jpg", price: 20 },
  { src: "https://i.imgur.com/iTLW1LL.jpg", price: 20 },
  { src: "https://i.imgur.com/9Api1ay.jpg", price: 20 },
  { src: "https://i.imgur.com/wvPDPOb.jpg", price: 20 },
  { src: "https://i.imgur.com/j3Gl6Tt.jpg", price: 20 },
  { src: "https://i.imgur.com/ObYWfsM.jpg", price: 20 },
  { src: "https://i.imgur.com/L2dlYbO.jpg", price: 80 },
  { src: "https://i.imgur.com/eKINdDj.jpg", price: 100 },
  // 密樂頓 異圖
  // { "src": "https://i.imgur.com/mOOQMiL.jpg", "price": 400 },
  { src: "https://i.imgur.com/LqIEdUr.jpg", price: 150 },
  { src: "https://i.imgur.com/vEz9jv7.jpg", price: 20 },
  { src: "https://i.imgur.com/7iMkMtT.jpg", price: 20 },
  { src: "https://i.imgur.com/p6o4mlE.jpg", price: 20 },
  { src: "https://i.imgur.com/F0s6Knq.jpg", price: 20 },
  { src: "https://i.imgur.com/iOy4ErZ.jpg", price: 250, des: '收三' },
  { src: "https://i.imgur.com/g61MQF7.jpg", price: 20 },
  { src: "https://i.imgur.com/FpHxIin.jpg", price: 20 },
  { src: "https://i.imgur.com/Lb8P9DM.jpg", price: 50 },
  { src: "https://i.imgur.com/ZFFSBAc.jpg", price: 50 },
  { src: "https://i.imgur.com/0huWqWB.jpg", price: 50 },
  { src: "https://i.imgur.com/GMrzPwc.jpg", price: 50 },
  // 喵喵 sar
  // { src: "https://i.imgur.com/lK1HMgE.jpg", price: 300 },
  { src: "https://i.imgur.com/MBE2BKp.jpg", price: 250 },
  { src: "https://i.imgur.com/6iAEpnU.jpg", price: 250 },
];
